transport/transport.go
=> Mark transport.go as deprecated

README.md
Appreciate all your work here. Just noticed a small error in the readme :)
=> Use gender neutral language in readme

README.md
Because it is really convenient.
=> README: link to godoc.org

examples/goproxy-sokeepalive/sokeepalive.go
Signed-off-by: ZhiFeng Hu <hufeng1987@gmail.com>
=> Fix err != nil check , must be err == nil

README.md
=> doc(readme): make basic example fully compilable

https.go
- Use half-close methods during copy
- Wait for the copy to be finished by waiting on a channel
I had a lot of `Error copying` errors on our servers for the https connections, in some cases client applications were failing with timeouts. At the moment second copy operation is failing because required half of the connection is closed by the first copy. It also worth waiting for the both copy operations to finish. Similar issue was recently fixed in go-socks5, in [this](https://github.com/armon/go-socks5/commit/66ca0497dfb58c4daaf663f53fc8bef7ded309be#diff-d9c546c27e20f6a2acfc4ac7b74c1a26) commit.
=> Improve copyAndClose implementation for https connections

examples/goproxy-customca/cert.go, examples/goproxy-customca/main.go
I saw that some people were asking for this so I'm sharing my code
=> added custom CA example

examples/go.mod, examples/go.sum, ext/go.mod, ext/go.sum, go.mod, go.sum
=> Add go.mod to make project Go modules compatible

examples/goproxy-transparent/transparent.go
RemoteAddr is empty within your transparent example.
And so I set RemoteAddr to CONNECT request to transparent example.
=> set RemoteAddr to CONNECT request on trasparent example

ctx.go, https.go, proxy.go
=> Fix `proxy` typo compile error

proxy_test.go
=> unit testing to response Content-Length. 

examples/goproxy-eavesdropper/main.go
=> fix a regular expression in eavesdropper example

examples/goproxy-eavesdropper/main.go
Otherwise the browser will wait forever.
=> Respond with 200 Ok on successful connection

examples/goproxy-certstorage/README.md, examples/goproxy-certstorage/main.go, examples/goproxy-certstorage/storage.go
=> sample certstorage

https.go, proxy.go, websocket.go
User-supplied ConnectDialWithReq can dial based on proxy requests
=> Pass ctx to connectDial

proxy.go
should pass updated req for remaining handlers
=> Bugfix in proxy.go while using multiple handlers

https.go
Port changes applied by https://github.com/SpectoLabs/goproxy to this project.
I edited them to strictly follow the HTTP specification and adapt them to this project.
=> Integrate Spectolabs fixes

https.go
Based on https://github.com/elazarl/goproxy/commit/2cb9e772acf36e8192867532ea431a50c03a2cfe
=> Close non persistent connection after first request

https.go
Apply https://github.com/hmarr/goproxy changes
=> Use original close conn value

doc.go, internal/signer/signer.go, proxy_test.go
In the last commit I forgot to push some changes.
I add them in this PR.
=> Add missing linting changes

proxy_test.go
The fork from Stripe added some proxy tests that we can port here to the upstream repository.
In this PR, I add their changes to this repository.
=> Add tests from Stripe fork

README.md
Fixes https://github.com/elazarl/goproxy/issues/584
=> Add error handling documentation

.github/dependabot.yml, README.md
- Ignore dependabot updates about new versions of this project in ext/ and examples
- Fixes https://github.com/elazarl/goproxy/issues/601
- Add versioning information, as explained in https://github.com/elazarl/goproxy/issues/599
=> Add case study in README

examples/redirect-https/README.md, examples/redirect-https/main.go
Fixes https://github.com/elazarl/goproxy/issues/45
=> Add https redirect example

.github/workflows/go.yml
Fixes https://github.com/elazarl/goproxy/issues/617
=> Enable race conditions detector

https.go
Fix discovered issues with https://github.com/elazarl/goproxy/pull/622
This is the beta 2 release.
=> Websocket fix

https.go, websocket.go
=> Websocket fix errors

README.md
I created a Telegram group to have a quick chat with the users about issues and features, more direct than issues and pull requests.
What do you think? @elazarl
=> Add telegram group community

proxy_test.go
Add a test to check the success of https://github.com/elazarl/goproxy/pull/634 and prevent future changes.
This change has been proposed by @thisislawatts in the other pull request.
=> Add MITM request cancel test

.golangci.yml, certs.go
Fixes https://github.com/elazarl/goproxy/issues/643
=> Add next protocols in default TLS configuration

README.md
Fix typo in example code snippet
=> Fix typo in example code snippet
