elazarl/goproxy

- https.go
If you want to filter proxy requests by who connected, the RemoteAddr field of the *http.Request needs to be populated on the *http.Request object when converting from a CONNECT request
> Adding in RemoteAddr field to requests converted from CONNECT

- dispatcher.go
- examples/goproxy-basic/README.md
- examples/goproxy-httpdump/README.md
- examples/goproxy-httpdump/httpdump.go
- examples/goproxy-jquery-version/README.md
- examples/goproxy-jquery-version/jquery_test.go
- examples/goproxy-jquery-version/main.go
- examples/goproxy-no-reddit-at-worktime/README.md
- examples/goproxy-no-reddit-at-worktime/noreddit.go
- ext/html/html.go
Hello,
Here is a little more documentation and cleanup of goproxy examples. It is far from done but this might help newcomers a bit. It certainly improved my understanding of goproxy by reading and tidying up some code. This is a cosmetic pass, some examples seem too complicated like the one logging HTTP content: the logging code, while interesting, seems a bit irrelevant and makes things harder by adding a lot of logic for clean process termination. I may go back to that once I have a clear picture of the remaining samples.
Also, what about gofmt'ing the code?
> More examples documentation

- examples/goproxy-httpdump/httpdump.go
This should fix https://github.com/elazarl/goproxy/issues/81
I did not touch it when refactoring the code because the intent was not clear to me. But according to the issue, you want to fail fast, which makes sense, then just let do that.
> httpdump: make TeeReadCloser.Close fail if either output fails

- https.go
Fixed the issue which goproxy doesn't provide correct HTTP request information from the context when HTTPS MITM is used.
> Context issue when HTTPS is used in MITM mode

- dispatcher.go
- https.go
URL.Path already has a leading slash, so adding our own slash causes strings.HasPrefix to fail.
> Remove extra slash from UrlHasPrefix

- dispatcher.go
Made a backwards-compatible change to allow the ReqCondition SrcIpIs to accept a list of IP addresses.
> Allow SrcIpIs to accept multiple parameters

- ext/html/html.go
Currently get warnings when getting `goproxy_html`.
```
warning: code.google.com is shutting down; import path code.google.com/p/go-charset/charset will stop working
warning: code.google.com is shutting down; import path code.google.com/p/go-charset/data will stop working
```
The author of `go-charset` has already moved to github, as evidenced by this commit:
https://github.com/rogpeppe/go-charset/commit/e9ff06f347d3f5d0013d59ed83754f0e88de10d4
> Update deps in advance of code.google.com shutdown

- https.go
It is currently impossible to authenticate with a proxy using
Proxy-Authenticate/Proxy-Authorization headers on a CONNECT method.
This adds support by allowing the user to specify a Hijack method that
provides the challenge header.
> Add customizable HTTPS proxy authentication

- https.go
Replaced body of responses which are processed via proxy.OnRequest().HandleConnect(goproxy.AlwaysMitm) are never closed.
> Close Body for MitM'ed connections

- https.go
- proxy.go
HTTP responses should be closed when done using them. It can dramatically improve the performance of HTTP requests/responses.
> close response bodies for reuse in http package

- https.go
- proxy_test.go
We use goproxy for our acceptance tests at Geckoboard and had some issue whereby requests to googleapis have duplicated scheme and host in the logs. After pairing with @achilleasa we identified the issue to be coming from [here](https://github.com/jnormington/goproxy/blob/master/https.go#L183)
On further investigation it appears that if the Opaque field on the url.URL struct is not blank and you call String() it will return the opaque value instead as shown  [here](https://github.com/golang/go/blob/master/src/net/url/url.go#L673-L707). 
Meaning that we now could potentially have a clash of two schemes and hosts in the forwarding request through the proxy. Below is an example from the spec.
Here is an example from the spec showing the problem with proxy.Verbose set to true
```
2016/08/15 …
```
> Fix case where url.String() can return full url from opaque field

- https.go
- proxy_test.go
Hey @elazarl,
Sorry I introduced another bug with the fix for opaque field - I didn't think it was possible to send a param with another url unencoded but that appears to not be the case, which when running the latest master of goproxy breaks some tests because of this change 😞 . As they have https:// in the url as a param that is not url encoded 😞  therefore when not an opaque field it bypasses rewriting the url.
```
2016-08-17_13:18:42.61837 2016/08/17 13:18:42 [049] INFO: Running 1 CONNECT handlers
2016-08-17_13:18:42.61838 2016/08/17 13:18:42 [049] INFO: on 0th handler: &{2 <nil> 0x536670} www.googleapis.com:443
2016-08-17_13:18:42.61850 2016/08/17 13:18:42 [049] INFO: Assuming CONNECT is TLS, mitm proxying it
2016-08-17_13:18:42.61853 2016/08/17 13:18:42 [049] INFO: signing for …
```
> Fix issue caused but checking if string contains https:// before rewriting

- https.go
HTTPS requests share the same `ProxyCtx` struct per `CONNECT` session. 
With PR a `ProxyCtx` is created for each request over an open connection, providing the ability to distinguish the individual requests and responses in an HTTPS session.
> Increment session number for https requests also

- https.go
This fixes #209 and causes Chrome to close the tunnel when the response is done.
> Make sure Connection: close is sent with MITM TLS responses

- README.md
Just a few spelling and semantic fixes in the README file.
Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))
> Spelling and semantic fixes in README.md

- ctx.go
Change "occured" to "occurred".
Sorry for all the small little spelling fixes. I've been using your library in one of my projects, and the grammar freak in me seems to catch every little one. Great library, by the way!
Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))
> Fix spelling error in ctx.go.

- proxy.go
The present behaviour is the drop all headers in the http.Response, which is our case causes issues with a set-cookie done before the proxy takes over. This PR adds an optional flag keeping the same behavior but allowing those to override if required
> Keep Response Headers

- ext/auth/basic.go
Hi!
Currently goproxy doesn't send any `Proxy-Connection` header in a HTTP 407 response, and the default HTTP/1.1 behaviour is to [keep the connection alive in that case](https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html).
However goproxy closes the connection, which breaks clients that expect to see a 407 response in order to negotiate the kind of HTTP authorization to send (Basic, NTLM, Digest), and then send a second request with proper `Proxy-Authorization`, because they expect the socket to be kept alive (as no `Proxy-Connection: close` is set, it's the default) and end up trying to write on a closed socket.
This fix adds the `Proxy-Connection: close` to 407 responses, however I'm not sure if it's the right place to put it.
Also I'm thinking ideally we would actually keep the …
> Send `Proxy-Connection: close` on unauthorized response

- https.go
We need this to track the request between "HandleConnect()" and "Do()".
> original ctx.UserData is needing in new ctx variable when MITM

- counterecryptor_test.go
This doubles the number of samples to reduce the variability of the stddev estimates.
> Fix issue 297: TestCounterEncStreamHistogram broken in go1.11.

- transport/transport.go
Removed unreachable code, renamed receiver
> Golint fixes

- logger.go
- proxy.go
This change allows usage of custom logging libraries like logrus etc instead of go standard log library.
In my case needed for logging warnings in json format.
> Added logger interface to allow usage of custom loggers

- ctx.go
- https.go
- proxy.go
- proxy_test.go
- signer.go
- signer_test.go
*Duplicate of #330, which I accidentally opened from the wrong branch. Unfortunately there doesn't seem to be a way to change the source branch, so I've had to re-create the PR.*
<hr>
Following on from the work @btwotch did in #284, this builds on their PR to address @oec's [comment](https://github.com/elazarl/goproxy/pull/284#issuecomment-434281454) (I encountered a similar issue).
To recap, the current implementation will regenerate TLS certificates every request. Generating certificates is computationally expensive, so this leads to performance issues when there are many requests to the same host.
@btwotch made it possible to add a custom certificate store to alleviate this issue. However, multiple concurrent requests to the same host would result in the certificate being generated …
> Pluggable certificate storage (following on from #284)

- proxy.go
- proxy_test.go
* fixes the panic if the response is from a handler is nil
* adds test case for handler response is nil
> Issue: #345 - fixes resp == nil:

- examples/go.sum
- go.mod
- go.sum
- signer.go
Creates a random certificate serial for each generated certificate. This prevents browsers seeing the same serial, for the same host, in two different certificates.
It is sufficient to use non-cryptographic random numbers for this task, hence the use of `math/rand`. If deterministic behaviour is needed (e.g. in tests), `rand.Seed()` can be called again.
This PR also includes some unavoidable changes to go.mod/go.sum files, without which the project cannot build (at least with Go 1.12).
Fixes #311.
> Random cert serial

- ctx.go
To more easily support something like:
```
HijackConnect(func(req *http.Request, client net.Conn, ctx *goproxy.ProxyCtx) {
// ...
remote, err := ctx.Proxy.ConnectDial("tcp", req.URL.Host)
// ...
})
```
> Export ProxyHttpServer

- https.go
#376  
Sending HTTP 200 to the client connection before invoking the todo.Hijack() method for a ConnectHijack action makes it impossible to cascade the http 502 (or any other error) back to the client in case we wanted to abort prematurely (e.g. the target address is unavailable)
[RFC 2817](https://tools.ietf.org/html/rfc2817#section-5.3) States: 
```
5.3 Establishing a Tunnel with CONNECT
Any successful (2xx) response to a CONNECT request indicates that the
proxy has established a connection to the requested host and port,
and has switched to tunneling the current connection to that server
connection.
```
It should be therefore up to the Hijack() method implementer to send the http 200 upon confirming that we can establish a tunnel.
> Don't return http 200 for ConnectHijack actions

- dispatcher.go
Adding a response condition for HTTP status codes.
Usage:
`proxy.OnResponse(statusCodeIs(301, 302, 303, 307, 308)).DoFunc(...`
> Add StatusCodeIs response condition

- dispatcher.go
Sorry about that! I added this method in a project that imported goproxy and figured I'd contribute it back... I forgot to remove the fully qualified method name.
> Forgot that this isn't a library like it was in my fork

- .github/workflows/go.yml
- README.md
@elazarl 
This pr can enable github actions to run testing for every PR.
I saw [some cases are broken](https://github.com/hoozecn/goproxy/actions/runs/87991669), so this pr can pass the check. But I don't really know how to fix them.
Your help will be appreciated
> Enable github actions ci

- README.md
Saw that RejectConnect wasn't working, but AlwaysReject behaved as expected.
> Fix method to deny connections in docs.

- README.md
- examples/goproxy-transparent/README.md
- examples/goproxy-transparent/transparent.go
First, I gratefully appreciate your easy-to-understand sample code!
It is very useful for me to gain knowledge to support HTTPS.
I'm afraid we can improve this example by avoiding using the deprecated function `Dial()`.
Other minor text corrections are included.
> Improve an example of transparent proxy: use DialContext() instead of Dial()

- https.go
The Signer will sign an invalid certificate when hostname is an IPV6 address
E.g :
Assuming the URL is https://[2606:4700:4700::1111]:443 , the CommonName of signed certificate will be: [2606 , the certificate is invalid.
this PR will fix the bug.
> Fix the signer signing an invalid certificate

- https.go
This commit changes to return `200 Connection established` instead `200 OK`.
```
Example of a response:
HTTP/1.0 200 Connection established
Proxy-agent: Netscape-Proxy/1.1
...data tunnelled from the server...
```
ref: https://datatracker.ietf.org/doc/html/draft-luotonen-web-proxy-tunneling-01#section-3.2
> fix: return `Connection established` instead `OK`

- https.go
There was another PR https://github.com/elazarl/goproxy/pull/339 fixing this issue.
This PR fixes it with a smaller change.
> Preserve Content-Length in header of HEAD response

- proxy.go
Flush response body for server-side events to avoid events buffering by goproxy.
I validated that it works with sse.
```
$ curl -x localhost:8080 localhost:3000/events
retry: 2000
id: 1
event: data
data: {"id":1,"data":"287039","time":"8:15:06 PM","final":false}
id: 2
event: data
data: {"id":2,"data":"267182","time":"8:15:07 PM","final":false}
id: 3
event: data
data: {"id":3,"data":"657946","time":"8:15:07 PM","final":false}
```
> Resolves #475

- signer.go
I fixed the cert date range  as follow:
```go
start := time.Unix(time.Now().Unix()-2592000, 0) // 2592000  = 30 day
end := time.Unix(time.Now().Unix()+31536000, 0)  // 31536000 = 365 day
```
> fix issue: #431 (ERR_CERT_VALIDITY_TOO_LONG)

- https.go
This data race requires quite of few conditions to appear.
1) The transport has to have HTTP/2 enabled (in goproxy, it's not by default). 
2) The target server must be an HTTP/2 one.
3) The request must have a body.
4) The server must return certain erroneus HTTP status code. 
5) The client must ignore Connection: close header from the proxy
(4ec79339bd51dec356e283d8c8de29748b42b1fe).
Somehow, I managed to hit all these conditions, and got this error:
panic: runtime error: slice bounds out of range [96:48]
goroutine 341699 [running]:
bufio.(*Reader).ReadSlice(0xc000b0c1e0, 0x80?)
/usr/local/go/src/bufio/bufio.go:347 +0x225
bufio.(*Reader).ReadLine(0xc000b0c1e0)
/usr/local/go/src/bufio/bufio.go:401 +0x27
net/textproto.(*Reader).readLineSlice(0xc0013400f0) …
> Fix data race in MITM'ed HTTPS request handling

- https.go
When `CONNECT` fails, other than getting a 502 response, there's no indication of the failure reason.
This pull request will:
1. Print the dial failure reason to the Go log output
2. Return the error in the 502 response body
I couldn't test this with curl as it suppresses the body for 5xx responses for some reason. Not sure if this is because this is a 502 in response to the CONNECT call.
Before:
```
% echo $'CONNECT nodns.boo HTTP/1.1\r\n' | nc localhost 8080
HTTP/1.1 502 Bad Gateway
```
After:
```
% echo $'CONNECT nodns.boo HTTP/1.1\r\n' | nc localhost 8080
HTTP/1.1 502 Bad Gateway
Content-Type: text/plain
Content-Length: 40
dial tcp: lookup nodns.boo: no such host
```
> httpError: write error string as body in 502 response

- proxy_test.go
Per RFC 6761, `example.com` is a standards-based choice for a functioning http site while the `.invalid` TLD will not exist.
> Clean up SimpleHttpRequest test.

- https.go
The tls client wasn't close when a handshake error occurs, this caused the proxy to keep a connection open without ever responding.
> Ensure tls client is closed if handshake fails

- go.mod
- go.sum
- h2.go
- https.go
- proxy.go
Add bare-bones HTTP2 "support" that allows goproxy to permit HTTP2 traffic through but doesn't apply proxy rules.
This also adds a dependency on the standard lib http2 package which, provided the current miniscule dep set, is worth giving some consideration.
> Add basic passthrough HTTP/2 support.

- ext/auth/basic.go
This allows falling through to a next `ConnectHandler` is authentication succeeds making if easier to combine with other `ConnectHandler`s.
Before this change the following code would not running the proxy in MITM mode, but instead directly connect to the remote host. 
```golang
auth.ProxyBasic(proxy)
proxy.OnRequest().HandleConnect(goproxy.AlwaysMitm)
```
@elazarl Another problem with the example above is that the `AlwaysMitm` applies all request handlers when roundtripping including the `auth.Basic` handler.  This means that for a `CONNECT` request the authentication will be checked twice, once by the `auth.BasicConnect` handler (good) and again by the `auth.Basic` one (bad). Somehow the `auth.Basic` handler should only be applied if there was no previous `CONNECT`. I'm not sure what …
> ext.auth: return `nil` instead of `OkConnect`

- https.go
- websocket.go
In a typical MitM over CONNECT scenario there is possibility to override request schema from secure to insecure. Example: when using TLS MitM we can substitute https service using a local http server by manipulating request URL schema in OnRequest handler.
But when there is a try to open websocket connection, there is an error - always secure TLS connection is enforced regardless to request URL schema. This PR fixes that.
Resolves #506
> Handle https to http override in TLS MitM websocket connection

- counterecryptor.go
- signer.go
Currently `TLSConfigFromCA()` returns an error if the specified custom CA certificate uses ED25519 as the private key.
With this pull request, I add the support for it.
Compared to rsa and ecdsa, its usage among the standard library doesn't use a pointer and it has been made clear in the x509 documentation: https://pkg.go.dev/crypto/x509#MarshalPKCS8PrivateKey (it explicitly says not a pointer)
> Add support for ED25519 CA cert key

- proxy.go
This PR updates the `copyHeaders` function to avoid the canonicalization of HTTP header keys caused by the `Add` method. Instead of using `Add`, the function now directly assigns header values from `src` to `dst`, preserving their original casing. 
Let me know if further adjustments are needed!
Closes: https://github.com/elazarl/goproxy/issues/403
> Avoid Header Canonicalization in copyHeaders by Using Direct Assignment

- dispatcher.go
- dispatcher_test.go
Without this patch IsLocalHost does not work for URLs with port specified i.e. it works for `http://localhost` but does not work for `http://localhost:80` or `http://localhost:10000`.
Fixes #487
> IsLocalHost: support host:port

- https.go
```go
httpsRegexp     = regexp.MustCompile(`^https:\/\/`)
if !httpsRegexp.MatchString(req.URL.String()) {
req.URL, err = url.Parse("https://" + r.Host + req.URL.String())
}
```
There is some code like above. In this case, it is a little bit inappropriate to use the regular expression. This regular expression is used to determine whether the url starts with https scheme. Here, a simple `HasPrefix` is fine
I write a benchmark to show this.
```go
var httpsRegexp = regexp.MustCompile(`^https:\/\/`)
// BenchmarkMatch-12       11180230                99.44 ns/op
func BenchmarkMatch(b *testing.B) {
b.Run("use-regex", func(b *testing.B) {
for i := 0; i < b.N; i++ {
httpsRegexp.MatchString("https://abc.abc.abc")
}
})
b.Run("use-prefix", func(b *testing.B) {
for i := 0; i < b.N; i++ { …
```
> Improve the https scheme matching

- README.md
- dispatcher.go
Fixes https://github.com/elazarl/goproxy/issues/561.
Since RFC4343 states that DNS host is case-insensitive by definition, we should do a case-insensitive comparison to perform actions on certain hosts, without let the user bypassing them by simply changing the case of a character.
The DNS will resolve both the uppercase and the lowercase host text to the same IP address.
Existing integration should never rely on the case of the host, so applying this change to the whole 
Proxy server should never care about the case of the host, so directly modifying `DstHostIs` function to do a case insenstiive compare is appropriate in this case.
> Case insensitive host comparison

- examples/go.mod
- examples/go.sum
- ext/go.mod
- ext/go.sum
- ext/limitation/concurrency.go
- ext/limitation/concurrency_test.go
- go.mod
- go.sum
Fixes https://github.com/elazarl/goproxy/issues/569.
Add request handler in the external package to pause the execution of a request handler when the limit of active requests is reached.
> Add concurrency limitation feature

- dispatcher.go
- dispatcher_test.go
- examples/cascadeproxy/main.go
- examples/goproxy-jquery-version/jquery_test.go
- examples/goproxy-transparent/transparent.go
- examples/goproxy-yui-minify/yui.go
- ext/auth/basic.go
- ext/auth/basic_test.go
- ext/html/html.go
- ext/html/html_test.go
- ext/image/image.go
- https.go
- proxy.go
- proxy_test.go
- regretable/regretreader.go
- regretable/regretreader_test.go
- responses.go
- signer_test.go
- transport/transport.go
- Replace deprecated package (ioutil) with io and os functions
- Reformat spacing of comments inside files
- Replace constant method names (e.g. "GET") with http library constants (e.g. http.MethodGet)
- Replace constant status codes (e.g. 200) with http library constants (e.g. http.StatusOK)
> Replace ioutil & magic numbers

- certs.go
- proxy.go
- signer.go
Based on https://github.com/elazarl/goproxy/pull/532, with additional optimizations.
- If the already parsed Leaf is present, use it in signHost instead of parsing the leaf certificate on every usage
- Return the whole CA certificate chain in TLSConfigFromCA
> Optimize CA certificate usage

- README.md
- examples/go.mod
- examples/go.sum
- examples/remove-https/README.md
- ext/go.mod
- ext/go.sum
- go.mod
- go.sum
Rewrite project readme to include new updates and make it more appropriate.
This PR also updates x/net dependency.
> Rewrite readme

- ext/image/image_test.go
- go.mod
- go.sum
- proxy_test.go
Resolves https://github.com/elazarl/goproxy/issues/576
> Move image manipulation tests to its external package

- ctx.go
- ext/go.mod
- ext/go.sum
- ext/html/html.go
- ext/html/html_test.go
Fixes https://github.com/elazarl/goproxy/issues/575
> Replace charset lib

- counterecryptor.go
- ctx.go
- examples/goproxy-httpdump/httpdump.go
- https.go
- logger.go
- proxy.go
Related to https://github.com/elazarl/goproxy/issues/564
> Integrate fixes from Stripe fork

- dispatcher.go
Currently the match inside `UrlHasPrefix` is done in the wrong way, since the URL.Path could also omit the initial "/" character.
Make sure to include it in the comparison.
Also, after the scheme, the `://` characters are needed.
> Fix prefix match

- dispatcher.go
Fixes https://github.com/elazarl/goproxy/issues/301.
According to our documentation, DstHostIs "returns a ReqCondition testing wether the host in the request url is the given string".
However, in the Go [documentation](https://pkg.go.dev/net/url#URL), Host can contain the host or the host:port combo, leading to an undefined behaviour.
To fix this issue, I call the [Hostname](https://pkg.go.dev/net/url#URL.Hostname) method instead.
The user can also specify a port that we need to match, and in this case, its considered in the handler.
> Fix DstHostIs check

- .golangci.yml
- README.md
- go.mod
- go.sum
- https.go
- internal/http1parser/header.go
- internal/http1parser/header_test.go
- internal/http1parser/request.go
- internal/http1parser/request_test.go
- proxy.go
Fixes https://github.com/elazarl/goproxy/issues/559.
Thanks to a suggestion made by @alessiodallapiazza, I found this thread where they talk about the request canonicalization problem: https://github.com/golang/go/issues/37834.
Basically, if the request specifies an header value, the Go http parser can rewrite its name to make it compliant with the RFC standard, but this behavior will break some requests made to websites that expects a different case (e.g. everything lowercase) for the name.
In this PR I tried to implement a (not too ugly) solution for this problem.
I still rely on the standard Go implementation, which handles all the edge cases, but I duplicate the data stream to parse manually only a list of the header names by ourselves.
To extract headers I used a simplified version …
> Prevent Request headers canonicalization

- .github/workflows/go.yml
This way it's one less place the version needs to be bumped.
Whenever the minimum version in `go.mod` is bumped, that will be immediately reflected here.
> Inherit `go` version from `go.mod` file

- .github/workflows/go.yml
`count=2` is very effective at sniffing out global state/singletons that don't get unset properly by a test's cleanup.
We started doing this at a previous employer and discovered all sorts of tests that were leaving global singleton artifacts around and other tests had started to depend on them... it took a while to untangle, but we were very glad once we finally got through it.
> Pre-emptively prevent test fixtures from lingering global state

- .github/workflows/go.yml
The actions names here are self-explanatory, no need to name them.
Plus the "checkout" name was slightly incorrect, as it checks out the full repo, and has nothing to do with the go modules directory.
> redundant names are redundant

- internal/signer/signer.go
Fixes https://github.com/elazarl/goproxy/issues/627
> Revert "Use same Subject of CA as the MITM certificate Subject"

- README.md
- examples/customca/README.md
Fixes https://github.com/elazarl/goproxy/issues/560.
Explains how to properly use root certificates with goproxy in your environment.
> Add root certificate trust documentation

- http.go
- https.go
- proxy.go
Currently we're calling the http response filter twice for the same request, as explained here: https://github.com/superfly/tokenizer/blob/a17a2e0a9dc0c37014e3477b977a4dd812bd23d1/tokenizer.go#L188.
We want to avoid that and in this pull request I remove the redundant one.
Moreover, when we receive the "Connection: close" header, we must wait for the client to close its connection, according to [RFC9112](https://httpwg.org/specs/rfc9112.html#persistent.tear-down), or there will be some issues with its response read. I therefore rollback the changes where we did an early return in the presence of this header and just wait for the client connection close.
> Fix http request handling

- examples/go.mod
- examples/go.sum
- examples/websockets/main.go
- http.go
- https.go
- proxy.go
- websocket.go
Fixes https://github.com/elazarl/goproxy/issues/630.
Instead of relying on custom code to handshake WebSockets separately, just rely on the standard library response Body, as explained in the documentation.
This will also use a cascadeproxy configuration by default, without the need to setting a custom per-request Dialer, when the custom transport is configured with a proxy URL.
I also update the websocket example to use a more updated WebSocket client library.
> Handle Websocket using standard library
